# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json

%YAML 1.1
---
AllCops:
  TargetRubyVersion: 3.0
  Exclude: []
  DisabledByDefault: true
  StyleGuideBaseURL: https://github.com/standardrb/standard

Lint/Syntax:
  Enabled: true
