# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json

%YAML 1.1
---
inherit_from: ./ruby-2.6.yml

AllCops:
  TargetRubyVersion: 2.5

Style/SlicingWithRange:
  Enabled: false

Lint/SuppressedExceptionInNumberConversion:
  Enabled: false
