# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json

%YAML 1.1
---
inherit_from: ./ruby-3.1.yml

AllCops:
  TargetRubyVersion: 3.0

Naming/BlockForwarding:
  Enabled: false

Style/NestedFileDirname:
  Enabled: false

Lint/RefinementImportMethods:
  Enabled: false
