# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json

%YAML 1.1
---
inherit_from: ./ruby-2.5.yml

AllCops:
  TargetRubyVersion: 2.4

Style/RedundantBegin:
  Enabled: false

Style/HashSlice:
  Enabled: false
