# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json

%YAML 1.1
---
inherit_from: ./ruby-1.9.yml

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  Enabled: false

Style/FileWrite:
  Enabled: false

Style/FileRead:
  Enabled: false

Layout/DotPosition:
  Enabled: false
