# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json

%YAML 1.1
---
inherit_from: ./ruby-3.0.yml

AllCops:
  TargetRubyVersion: 2.7

Style/HashExcept:
  Enabled: false

Style/RedundantInterpolationUnfreeze:
  Enabled: false
