# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json

%YAML 1.1
---
inherit_from: ./ruby-3.2.yml

AllCops:
  TargetRubyVersion: 3.1

Style/DataInheritance:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false
  AllowOnlyRestArgument: true
