# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json

%YAML 1.1
---
inherit_from: ./ruby-2.4.yml

AllCops:
  TargetRubyVersion: 2.3

Style/ComparableClamp:
  Enabled: false

Style/DirEmpty:
  Enabled: false
