#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "standard"

warn <<-WARNING.gsub(/^ {2}/, "")
  Error: Run 'standardrb' instead of 'standard'. We have renamed the gem's binary
  to avoid naming conflicts with the StandardJS 'standard' bin in the event both
  are on a user's PATH.

  The 'standard' bin and this notice will be removed in an upcoming release.
WARNING
exit 1
